# Generated by Django 3.2.16 on 2022-11-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darshanabook',
            fields=[
                ('da_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ppls', models.IntegerField()),
            ],
            options={
                'db_table': 'darshanabook',
                'managed': False,
            },
        ),
    ]
