# Generated by Django 3.2.16 on 2022-11-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('prathishta', models.CharField(max_length=50)),
                ('estd', models.CharField(db_column='Estd', max_length=5)),
                ('history', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'temple',
                'managed': False,
            },
        ),
    ]
